"""Storage Protocol — local DuckStore ↔ RemoteStore (HTTP) swap 가능.

미래 Qdrant/Neo4j adapter 도 이 Protocol 을 만족하면 g CLI 는 그대로 작동.
"""

from __future__ import annotations

from typing import Iterable, Protocol, runtime_checkable

from gstar.schema import Cluster, Edge, EmergenceEvent, Goal, Namespace, Node


@runtime_checkable
class KnowledgeStore(Protocol):
    """G 의 영속 저장 추상화. DuckStore 와 RemoteStore 가 둘 다 구현."""

    def insert_node(self, node: Node) -> None: ...
    def get_node(self, node_id: str) -> Node | None: ...
    def list_nodes(
        self, kind: str | None = None, namespace: str | None = None, limit: int | None = None,
    ) -> list[Node]: ...
    def count_nodes(self) -> int: ...
    def nodes_by_namespace(self, namespace: str) -> list[Node]: ...

    def insert_edge(self, edge: Edge) -> None: ...
    def edges_of(self, node_id: str) -> list[Edge]: ...
    def degree(self, node_id: str) -> int: ...

    def insert_goal(self, goal: Goal) -> None: ...
    def get_goal(self, goal_id: str) -> Goal | None: ...
    def list_goals(self) -> list[Goal]: ...

    def insert_cluster(self, cluster: Cluster, member_gravity: dict[str, float]) -> None: ...
    def clusters_for_goal(self, goal_id: str) -> list[Cluster]: ...
    def get_cluster(self, cluster_id: str) -> Cluster | None: ...
    def cluster_members(self, cluster_id: str) -> list[tuple[str, float]]: ...
    def update_cluster_merkle(self, cluster_id: str, merkle_root: str) -> None: ...

    def insert_emergence(self, ev: EmergenceEvent) -> None: ...
    def emergence_for_goal(self, goal_id: str) -> list[EmergenceEvent]: ...

    def log_selection(
        self, goal_id: str, cycle: int, entries: Iterable[tuple[str, float, bool]],
    ) -> None: ...
    def repeat_selection_rate(
        self, goal_id: str, node_id: str, last_n: int = 5,
    ) -> float: ...

    def upsert_namespace(self, ns: Namespace) -> None: ...
    def list_namespaces(self) -> list[Namespace]: ...
    def active_namespace(self) -> str: ...
    def set_active_namespace(self, name: str) -> None: ...


@runtime_checkable
class VectorIndex(Protocol):
    """임베딩 벡터 인덱스. FAISS / Qdrant 등."""

    dim: int

    def __len__(self) -> int: ...
    def add(self, node_id: str, vector) -> None: ...
    def add_batch(self, node_ids: list[str], vectors) -> None: ...
    def search(self, vector, k: int) -> list[tuple[str, float]]: ...
    def save(self) -> None: ...
