{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-frontend
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.fullname" . }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://{{ include "app.fullname" . }}-backend:{{ .Values.springBackend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-frontend
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.fullname" . }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
{{- end }}
