apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secrets
type: Opaque
stringData:
  postgresPassword: {{ .Values.secrets.postgresPassword | quote }}
  grafanaPassword: {{ .Values.secrets.grafanaPassword | quote }}
